hashicorp/terraform-provider-boundary

docs/index.md
This PR adds the port to the example `addr` to be consistent with the `addr` listed earlier.
=> docs: add port to example `addr`

CHANGELOG.md, docs/resources/account.md, internal/provider/resource_account.go
Removes update path for account passwords during `terraform apply`
This means if a user makes a change to the default password in their `.tf` file, it will be applied to future users created, previously created users will keep their password.
```
resource "boundary_account" "users_acct" {
for_each       = var.users
name           = each.key
description    = "User account for the person named ${each.key}"
type           = "password"
login_name     = lower(each.key)
password       = "password"   <--------------- I.E. user changes this
auth_method_id = boundary_auth_method.password.id
}
```
=> Dont allow password change via tf apply

docs/resources/target.md, examples/resources/boundary_target/resource.tf
Per #78, this is a simple change to include the boundary_target connection 'type' in the documentation. This is a required attribute, and creates some distinction about 'type' here, vs the 'type' attribute in the boundary_host and boundary_host_set resources.
=> Include the 'type' attribute in the boundary_target documentation example.

CHANGELOG.md, docs/resources/managed_group.md, docs/resources/target.md, examples/resources/boundary_target/resource.tf, internal/provider/resource_managed_group.go, internal/provider/resource_target.go, internal/provider/resource_target_test.go
- Adds support for new target fields `application_credential_source_ids` and `host_source_ids` 
- Deprecates `application_credential_library_ids` and `host_library_ids`
=> Deprecate target host_set_ids and credential_library_ids

internal/provider/resource_role.go, internal/provider/resource_role_test.go
Fixes https://github.com/hashicorp/boundary/issues/1752, I was going to transfer the issue to this repo but I have some questions of follow up work in Boundary that I will discuss with the team.
I also manually validated this as follows:
In a local tf file with a new role and `u_fakeuser` defined as principal:
```
resource "boundary_role" "role_with_bad_principal" {
name     = "role_with_bad_principal"
scope_id = boundary_scope.org.id
grant_strings = [
"id=*;type=auth-method;actions=list,authenticate",
"type=scope;actions=list",
"id={{account.id}};actions=read,change-password"
]
principal_ids = ["u_fakeuser"]
}
```
And then running `terraform apply` leads to:
```
Error: error setting principals
on main.tf line 93, in resource "boundary_role" "role_with_bad_principal":
93: resource …
```
=> feat(role): Support partial success in role create/update

internal/provider/resource_account_oidc.go
Fix the Issuer and Subject mapping from the API for an OIDC Account.
I hope it's not a too quick and dirty Fix, but it works for the latest Boundary version.
This Pull Request can solve the issue https://github.com/hashicorp/terraform-provider-boundary/issues/151
=> Map Issuer and Subject from attributes elements

internal/provider/resource_auth_method.go
As of now (2022-02-26)、curretly the `password` or `oidc` type is supported. 
Thus, I added a validation func to check on validation.
=> Add validate func for auth method type key

.github/workflows/release.yml, .goreleaser.yml, .tfproto5, terraform-registry-manifest.json
Internal RFC References:
* ENGSRV-035
* ENGSRV-064
* SEC-036
* SEC-061
* TF-279
_Please note: This process can be adjusted to suit your needs, but it will require changes to the workflow setup._
The initial release workflow submitted here is triggered by pushing a semantic version tag prepended with a `v` to the repository. For example:
```shell
git switch main # or your release branch
git pull
git tag v1.2.3
git push origin v1.2.3
```
The most important distinction from the TeamCity release process is that the repository must be fully prepared for the release, including the `CHANGELOG.md` file. Providers can decide the most appropriate process to manage the CHANGELOG or any release notes as part of this new process. This initial workflow will automatically grab contents from the top of …
=> Migrate Provider Releases from TeamCity to GitHub Actions

.github/workflows/release.yml, .goreleaser.yml, .release/release-metadata.hcl
This reflects the changes that acccompany the releases-api anticipated to be launched in early May. Included is:
*    Version bump of the terraform provider release gh action
*    Variables added for interfacing with releases-api
*    hc-releases syntax modified for releases-api use
*    metadata file added for ingesting with releases-api
=> [DO NOT MERGE] changes for releases-api launch

docs/resources/role.md, internal/provider/resource_role.go
Fixes #130 
The `default_role` was removed from Boundary pre-launch to avoid ambiguity on the meaning of `default`. The behavior was however never removed from the Terraform Provider. 
This is not being deprecated because it was never supported.
=> Remove default_role from role

internal/provider/resource_target.go
When updating a target with different credential sources, the credential types that had changed from the state file were applied. Since we are using the SetCredentialSources function, any credential ids that are stored in the state file, but have not changed would be lost.
Gather all the credential ids when performing a SetCredentialSource action.
=> fix: set target credentials on update

docs/resources/account.md, docs/resources/account_password.md, docs/resources/auth_method_oidc.md, docs/resources/credential_ssh_private_key.md, docs/resources/credential_username_password.md, internal/provider/resource_account.go, internal/provider/resource_account_password.go, internal/provider/resource_auth_method_oidc.go, internal/provider/resource_credential_ssh_private_key.go, internal/provider/resource_credential_username_password.go
Setting variables that are secrets to sensitive so they are not printed out to the terminal
=> fix: set secret variables to senitive

internal/provider/resource_credential_store_vault.go
Created a Vault store, expired it in Vault and waited for Boundary to expire to token. I then ran `terraform apply` which lead to the panic:
```
anic: interface conversion: interface {} is nil, not string
2022-09-27T16:48:09.875-0700 [DEBUG] plugin.terraform-provider-boundary:
2022-09-27T16:48:09.875-0700 [DEBUG] plugin.terraform-provider-boundary: goroutine 140 [running]:
2022-09-27T16:48:09.875-0700 [DEBUG] plugin.terraform-provider-boundary: github.com/hashicorp/terraform-provider-boundary/internal/provider.setFromVaultCredentialStoreResponseMap(0xc000209310?, 0x4fc9188?, 0x1)
2022-09-27T16:48:09.875-0700 [DEBUG] plugin.terraform-provider-boundary: 	/Users/louisruch/terraform-provider-boundary/internal/provider/resource_credential_store_vault.go:146 +0x525
```
Rebuilt with the new code …
=> bug(vault): Fix panic after token expires

docs/resources/target.md, internal/provider/resource_target.go
Removing the deprecated flag application_credential_sources_ids from the target resource.
=> fix: remove deprecated flag application_credential_sources_ids

CHANGELOG.md, internal/provider/provider.go
When creating the boundary terraform provider:
```
provider "boundary" {
addr                            = "http://127.0.0.1:9200"
auth_method_id                  = "ampw_1234567890" 
password_auth_method_login_name = "admin"          
password_auth_method_password   = "password"       
}
```
When an error is returned from a failed authentication, we describe the raw api response. Example:
```
Error: {"kind":"NotFound", "message":"Resource not found."}
│ 
│   with provider["registry.terraform.io/hashicorp/boundary"],
│   on main.tf line 10, in provider "boundary":
│   10: provider "boundary" {
```
This error is not really helpful and the true source of the issue is an invalid auth method id.
Perform an api error casting check from the authentication request. On a 401 return an error …
=> fix: improve error message for invalid provider credentials

CHANGELOG.md, internal/provider/resource_group.go, internal/provider/resource_host_set_static.go, internal/provider/resource_role.go, internal/provider/resource_target.go, internal/provider/resource_target_test.go, internal/provider/resource_user.go
The following resources have one or more subtasks when applying the terraform creation task: group, host set, role, target, user. For example, when creating a target the following steps are invoked:
1. Create the target
2. Associate host sources to the target
3. Associate credential sources to the target
Each step is a different call to the boundary API. Currently there is a bug where if I provide an invalid credential source to the target the state file does not save any information about the target. When resolving the error in the terraform source file and then reapplying the changes, boundary will return the following error: `unique name violation`. This is because we only set the state at the end of the creation function and the state is never set if the happy path is not followed. …
=> fix: save resource state when failing on subtasks

CHANGELOG.md, docs/resources/auth_method_oidc.md, internal/provider/resource_auth_method_oidc.go, internal/provider/resource_auth_method_oidc_test.go
Previously, setting 0 as a value for maxAge in an OIDC resource block would not update Boundary, as it was getting treated as a nil value in the provider. 
This fix addresses that issue, ensuring that both setting the value to 0 will require immediate reauthorisation, as well as removing the maxAge paramater defaulting the reauth time length to the TTL of the chosen OIDC provider.
=> fix: Allow users to set OIDC maxAge value to 0 to require immediate reauth

internal/provider/resource_account_ldap_test.go, internal/provider/resource_account_password_test.go, internal/provider/resource_account_test.go, internal/provider/resource_auth_method_password_test.go, internal/provider/resource_auth_method_test.go, internal/provider/resource_credential_json_test.go, internal/provider/resource_credential_library_vault_ssh_certificate_test.go, internal/provider/resource_credential_library_vault_test.go, internal/provider/resource_credential_ssh_private_key_test.go, internal/provider/resource_credential_store_static_test.go, internal/provider/resource_credential_store_vault_test.go, internal/provider/resource_credential_username_password_test.go, internal/provider/resource_host_catalog_plugin_test.go, internal/provider/resource_host_catalog_static_test.go, internal/provider/resource_host_set_plugin_test.go, internal/provider/resource_host_set_static_test.go, internal/provider/resource_managed_group_ldap_test.go, internal/provider/resource_managed_group_test.go
There was a decent amount of repeated code between similar test suites, consolidated them into a few more common tests. 
Also fixed a flaky test in `TestAccCredentialLibraryVault`
=> refactor: reduce some repeated code in tests

CHANGELOG.md, internal/provider/resource_credential_store_vault.go
=> feature: add worker_filter option to Boundary Credential Store Vault

docs/resources/managed_group.md
From a [Slack conversation](https://hashicorp.slack.com/archives/C016ZKNM05T/p1679436965102879), the description for the `boundary_managed_group` resource mistakenly says that the filter is a Boolean expression to filter **workers**. It actually filters **users**. This pull request fixes the typo.
=> docs: Fix typo in Managed Group resource page

CHANGELOG.md, go.mod, go.sum, internal/provider/provider.go, internal/provider/provider_test.go, internal/provider/resource_account_ldap_test.go, internal/provider/resource_auth_method_ldap_test.go
- Enable LDAP authentication through TF Provider
- Enable easier LDAP authentication by automatically setting the `auth_method_id` for the Terraform provider if LDAP is the primary auth method or only auth method.
- Combine fields for auth_method `login_name` & `password`
- Bump up `github.com/jimlambrt/gldap` & `github.com/hashicorp/boundary` to pull in needed changes for TF changes
```
provider "boundary" {
addr                            = "http://127.0.0.1:9200"
auth_method_login_name = "myuser"
auth_method_password   = "passpass"
}
```
```
provider "boundary" {
addr                            = "http://127.0.0.1:9200"
auth_method_login_name = "myuser"
auth_method_password   = "passpass"
scope_id                        = "s_1234567890"
}
```
```
provider "boundary" {
addr …
```
=> feature: Add support for using ldap primary auth method

internal/provider/resource_credential_library_vault.go
Fixes a bug where if the `credential_type` in a `boundary_credential_library_vault` resource is changed, TF will register the change and report that the resource was updated but doesn't actually change `credential_type`.
This is because `credential_type` is immutable in Boundary and we don't take it into account when updating a `boundary_credential_library_vault` resource, so this isn't actually valid operation.
I wasn't able to write tests for this, but I was able to manually validate it
=> fix(credlib): Force new resource on credential_type change

examples/resources/boundary_account_password/resource.tf, internal/provider/resource_account_password.go, internal/provider/resource_account_password_test.go
The `boundary_account_password` resource in the boundary provider has a required `type` field but the only valid value is "password." Deprecating the `type` field and setting a default value. Users will still be able to pass in a value for the `type` field. This will prevent existing configs from breaking.
Example: The missing `type` field will default to `password`.
```
resource "boundary_account_password" "jeff" {
auth_method_id = boundary_auth_method.password.id
login_name     = "jeff"
password       = "$uper$ecure"
}
```
=> chore: Deprecate type field for boundary_account_password

internal/provider/provider.go, internal/provider/provider_test.go, internal/provider/resource_auth_method_oidc_test.go
- Add test coverage for authenticating with recovery kms mechanism & an auth method that is not a `password` auth-method
- Skip fetching default auth method when `recovery_kms_hcl` is set or the client token isn't null
- Set `boundary_auth_method_oidc.foo` test resource's scope to "global" to easily allow testing the default auth method
- Removed `auth_method_id`, `password_auth_method_login_name` & `password_auth_method_password` from `testConfigWithRecovery` since those fields are not needed for authenticating with [Recovery KMS](https://developer.hashicorp.com/boundary/docs/oss/installing/no-gen-resources#recovery-kms-workflow). Using those fields also previously caused tests to pass with the bug.
This should cover test coverage for the bug raised: …
=> fix: default auth method with recovery kms

internal/provider/resource_account_oidc_test.go, internal/provider/resource_account_test.go
There isn't any unit test coverage for `boundary_account_oidc`. Adding test coverage for it
=> chore: add test coverage for boundary_account_oidc

docs/resources/host_set_plugin.md, examples/resources/boundary_host_set_plugin/resource.tf
This change is to update the example docs for `host_set_plugin` filters attribute to use a list strings instead of just strings.
WIthout using a list of strings, Terraform will falsely detect diffs with host set plugin`filters`.
AWS host set plugin expects filters attributes to be passed as a list of strings instead of strings. It is currently backwards compatible with strings due to the migration [normalizeData func](https://github.com/hashicorp/boundary-plugin-aws/blob/7bf9fe2ecf1f20d7ff8aea8306909abcde1d17a4/plugin/service/host/plugin.go#L256) on AWS host plugin.
Previously this was not working onCreate but [Boundary PR-3338](https://github.com/hashicorp/boundary/pull/3338) fixed the bug.
=> docs: update host set plugin filters examples

CHANGELOG.md, docs/resources/target.md, examples/resources/boundary_target/resource.tf, internal/provider/resource_target.go
- add new optional `enable_session_recording` field for enabling or disabling session recording
- add new optional `storage_bucket_id` field for setting the storage bucket for the target
- These new fields are applicable to Boundary HCP/ENT
- There is no test coverage yet until we add support for testing enterprise-only features. Manually tested the changes
=> feat: add target resource session recording support

internal/provider/resource_storage_bucket.go
During terraform `storage_bucket` resource update, the default worker filter option used is the `DefaultBucketName` instead of `DefaultWorkerFilter`. Update it to use the correct option
=> fix: Append correct storage bucket worker filter option

docs/resources/worker.md, examples/resources/boundary_worker/resource.tf
The current `boundary_worker` resource example incorrectly references a `boundary_self_managed_worker ` resource that doesn't exist.
This change corrects the resource in the example.
https://registry.terraform.io/providers/hashicorp/boundary/1.1.9/docs/resources/worker
=> Correct `boundary_worker` resource example

.github/workflows/actionlint.yml, .github/workflows/test.yml
Just run tests on ubuntu-latest, so they will succeed for external contributors.
=> chore: fix test workflow for external contributors

README.md
Seems Go 1.21> is required to develop the provider: 
```
bouhmad :: ~/terraform-provider-boundary ‹main*› » make testacc                  
TF_ACC=1 go test ./... -v  -timeout 120m
../go/pkg/mod/github.com/hashicorp/boundary@v0.13.1-0.20231012004550-1ed0a13004b9/internal/event/sink_config.go:9:2: package slices is not in GOROOT (/usr/local/go/src/slices)
note: imported by a module that requires go 1.21
FAIL    github.com/hashicorp/terraform-provider-boundary/internal/provider [setup failed]
?       github.com/hashicorp/terraform-provider-boundary        [no test files]
?       github.com/hashicorp/terraform-provider-boundary/plugins/kms    [no test files]
```
After upgrading go to 1.21, I was able to run make testacc successfully.
=> Update Go & Terraform version requirement in README

Makefile
I was running into the following error when running `make test-database-up`
```
❯ make test-database-up
Using image:                       docker.io/hashicorpboundary/postgres:11-alpine
Additional postgres configuration: 
Using volume:                      ~/go/pkg/mod/github.com/hashicorp/boundary@v0.13.1-0.20231012004550-1ed0a13004b9/internal/db/schema/migrations:/migrations
docker: Error response from daemon: create ~/go/pkg/mod/github.com/hashicorp/boundary@v0.13.1-0.20231012004550-1ed0a13004b9/internal/db/schema/migrations: "~/go/pkg/mod/github.com/hashicorp/boundary@v0.13.1-0.20231012004550-1ed0a13004b9/internal/db/schema/migrations" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use …
```
=> chore: Fix path error

docs/data-sources/user.md, docs/resources/host_set.md, docs/resources/target.md, examples/data-sources/boundary_user/data-source.tf, examples/resources/boundary_host_set/resource.tf, examples/resources/boundary_target/resource.tf
This PR addresses some issues in the documentation. 
1. Per https://github.com/hashicorp/terraform-provider-boundary/pull/492, the `boundary_scope` data source uses `scope_id` as a parameter (and not `parent_scope_id`)
2. The `boundary_host` data source does not have `scope_id` as a parameter: https://github.com/hashicorp/terraform-provider-boundary/blob/main/internal/provider/resource_host_static.go#L34
=> doc: Fix linter errors

.github/workflows/test.yml, internal/provider/resource_credential_store_vault_test.go
[ICU-11525](https://hashicorp.atlassian.net/browse/ICU-11525)
Originally, the test `TestAccCredentialStoreVault` was flaky for the following reason
> === RUN   TestAccCredentialStoreVault
>     resource_credential_store_vault_test.go:101: Step 1/8 error: Error running apply: exit status 1
>         Error: error creating credential store: {"kind":"Internal", "message":"credentialstores.(Service).createInRepo: unable to create credential store: vault.(Repository).CreateCredentialStore: unable to lookup vault token: vault.(client).lookupToken: vault: http://localhost:32796: unknown: error #0: Error making API request.\n\nURL: GET http://localhost:32796/v1/auth/token/lookup-self\nCode: 400. Raw Message:\n\nClient sent an HTTP request to an HTTPS server.\n"}
>           with …
=> test: Fix failure in TestAccCredentialStoreVault

docs/resources/storage_bucket.md, examples/resources/boundary_storage_bucket/resource.tf
Update example for dynamic credential for storage bucket to include `disable_credential_rotation` attribute. `disable_credential_rotation` needs to be set to `true` when configuring dynamic credentials
=> docs: Add required field for storage bucket example

.github/workflows/jira.yml, .github/workflows/release.yml
This PR updates some GitHub Actions to use a Node20 version of the Action in order to avoid deprecation warnings.
Modifications to the JIRA workflow were tested here: https://github.com/hashicorp/boundary-ui/pull/2283
=> chore: Update to use Node20 version of Actions

README.md, docs/index.md, examples/provider/provider.tf, internal/provider/provider_test.go
The `password_auth_method_login_name` and `password_auth_method_password` arguments are deprecated in favor of `auth_method_login_name` and `auth_method_password`.
=> chore: replace deprecated arguments in provider example

.github/workflows/jira.yml
This PR updates the use of `hub` in the `jira.yml` workflow. The command is no longer available by default, and the suggestion is to update to use the `gh` command. It would cause this step of the workflow to constantly fail, which would create a JIRA ticket for every PR opened, even if the user was internal.
Example:
```
/home/runner/work/_temp/7e8d2cb7-1460-4712-ae87-25df58ee7218.sh: line 2: hub: command not found
Actor moduli is not a boundary team member
```
I also needed to update the `JIRA_SYNC_GITHUB_TOKEN` secret with a new token (borrowing the same one used in `boundary-ui`)
A similar change was applied in the boundary-ui repo in this PR: https://github.com/hashicorp/boundary-ui/pull/1729/files
=> chore: Update use of deprecated `hub` command

.github/dependabot.yml
This PR updates the dependabot configuration to only provide updates for internal Github Action updates. We have an internal tool to provide security approved 3rd party Action updates, so the PRs generated by dependbot are redundant.
This is similar to the update made here: https://github.com/hashicorp/boundary/pull/5414
=> chore: Only use dependabot for internal action updates

.github/dependabot.yml
Grouping prevents many different PRs from being opened at once.
=> dependabot: add groups
